<div class="main-content">
    <div class="content-wrapper"><!--Statistics cards Starts-->
      <div class="row">
        <div class="col-sm-12">
          <section id="fabs-examples">
            <div class="row">
              <div class="col-12 mt-3 mb-1">
                <div class="content-header">Ticketing Management system
                  <?php if($this->session->userdata('role') == 'customer') { ?>
                    <a href="<?=site_url('admin/add_new_ticket')?>" class="btn btn-primary pull-right">Generate New Ticket</a>
                  <?php } ?>
                </div>
                <p class="content-sub-header">Following are the tickets generated by the customers </p>
                <!-- <p class="content-sub-header">Following are the tickets generated by you </p> -->


                <?php if($this->session->flashdata('success')) { ?>
                  <div class="alert alert-success alert-dismissible">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <?=$this->session->flashdata('success')?>
                  </div>
                <?php } ?>
              </div>
            </div>

            <?php foreach($tickets as $ticket) { ?>
              <!-- Ticket start -->
              <div class="row">
                <div class="col-sm-12">
                  <div class="card">
                    <div class="card-body">
                      <div class="card-block">
                        <br>
                        <div class="row">
                          <div class="col-md-12">
                            <h3><?=$ticket['title']?></h3>
                            <p><?=$ticket['issue']?></p>
                          </div>
                        </div>
                        <hr>
                        <div class="row">
                          <div class="col-md-3">
                              <label>Ticket Number: </label>
                          </div>
                          <div class="col-md-5">
                            <a href="javascript:void(0)"><?=$ticket['ticket_number']?></a>
                          </div>
                          

                          <div class="col-md-4">
                            <?=date('d-M-Y  H:i a', strtotime($ticket['datetime']))?>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-md-3">
                              <label>Customer Name: </label>
                          </div>
                          <div class="col-md-5">
                            <?=$ticket['customer_name']?>
                          </div>
                          <div class="col-md-4">
                            <?php if($ticket['status'] == 'new') { ?>
                              <span class="badge badge-warning"><?=$ticket['status']?></span>
                            <?php } elseif($ticket['status'] == 'active') { ?>
                              <span class="badge badge-info"><?=$ticket['status']?></span>
                            <?php } else { ?>
                              <span class="badge badge-success"><?=$ticket['status']?></span>
                            <?php } ?>
                          </div>
                        </div>
                        <br>
                        <div class="row">
                          <div class="col-md-12">
                            <a href="<?=site_url('admin/view_ticket/'.$ticket['id'])?>" class="btn btn-success">View Ticket</a>
                            <a href="<?=site_url('admin/delete_ticket/'.$ticket['id'])?>" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this ticket? All Replies to that ticket will be deleted as well');">Delete</a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Ticket ends -->
            <?php } ?>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>
